# code echo /home/gitpod/.dbt/profiles.yml
dbtCustomerOrders:
  outputs:

    dev:
      type: sqlite
      threads: 1
      database: dbtCustomerOrders.db
      schema: 'main'
      schemas_and_paths:
        main: 'dbtCustomerOrders.db'
      schema_directory: 'dbtCustomerOrders/data'
      # optional: list of file paths of SQLite extensions to load. see README for more details.
      # extensions:
      #   - '/path/to/sqlean/crypto.so'
      #   - '/path/to/sqlean/math.so'
      #   - '/path/to/sqlean/text.so'

    prod:
      type: sqlite
      threads: 1
      database: dbtCustomerOrders.db
      schema: 'main'
      schemas_and_paths:
        main: 'dbtCustomerOrders.db'
      schema_directory: 'dbtCustomerOrders.db/data'
      # optional: list of file paths of SQLite extensions to load. see README for more details.
      # extensions:
      #   - '/path/to/sqlean/crypto.so'
      #   - '/path/to/sqlean/math.so'
      #   - '/path/to/sqlean/text.so'

  target: dev