
version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: customers
      - name: orders
      - name: order_items

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: stg_customers
    description: "Cleaned up customers data"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: "Orders with cleaned fields"
  - name: stg_order_items
    description: "Order items details"